//AUTH
export const LOGIN_SUCCESS ='LOGIN_SUCCESS'
export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS'
export const START_LOADING ='START_LOADING'
export const REGISTER_SUCCESS ='REGISTER_SUCCESS'
export const LOGIN_FAIL ='LOGIN_FAIL'

//UI
export const COLLAPSE_NAVBAR ='COLLAPSE_NAVBAR'

 //EQUIPOS
 export const CREATE_NEW_EQUIPMENT ='CREATE_NEW_EQUIPMENT'
 export const CHECK_EQUIPMENT ='CHECK_EQUIPMENT'

 //PATRONES
 export const CHECK_PATTERN ='CHECK_PATTERN'
 export const CLEAN_CHECKING ='CLEAN_CHECKING'

 //RESPONSABLES
 export const OBTNER_RESPONSABLES='GET_RESPONSABLES'
 export const AGREGAR_NUEVO_RESPONSABLE='AGREGAR_NUEVO_RESPONSABLE'

 //UBICACIONES
 export const GET_LOCATIONS='GET_LOCATIONS'
 export const ADD_NEW_LOCATION='ADD_NEW_LOCATION'

//Unidad Medidas
export const GET_UNIT_MEASURE='GET_UNIT_MEASUARE'
export const ADD_NEW_UNIT_MEASURE='ADD_NEW_UNIT_MEASURE'

//obtener magnitudes
export const OBTENER_MAGNITUDES ='OBTENER_MAGNITUDES '
export const AGREGAR_NUEVA_MAGNITUD = 'AGREGAR_NUEVA_MAGNITUD'

//Frecuencias
export const AGREGAR_NUEVA_FRECUENCIA ='AGREGAR_NUEVA_FRECUENCIA '
export const OBTENER_FRECUENCIAS ='OBTENER_FRECUENCIAS '
