//AUTH
export const LOGIN_SUCCESS ='LOGIN_SUCCESS'
export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS'
export const START_LOADING ='START_LOADING'
export const REGISTER_SUCCESS ='REGISTER_SUCCESS'
export const LOGIN_FAIL ='LOGIN_FAIL'

//UI
export const COLLAPSE_NAVBAR ='COLLAPSE_NAVBAR'

 //EQUIPOS
 export const CREATE_NEW_EQUIPMENT ='CREATE_NEW_EQUIPMENT'

 //PATRONES
 export const CHECK_PATTERN ='CHECK_PATTERN'
 export const CLEAN_CHECKING ='CLEAN_CHECKING'

